# Generated by Django 5.1.6 on 2025-04-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0019_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
