# Generated by Django 5.1.6 on 2025-04-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0020_enquirytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arttable',
            name='price',
            field=models.IntegerField(),
        ),
    ]
